language: haskell

ghc:
  - 7.4
  - 7.6
  - 7.8

install:
 - mkdir sandbox
 - cabal sandbox init --sandbox sandbox
 - cabal sandbox add-source microlens
 - cabal sandbox add-source microlens-mtl
 - cabal sandbox add-source microlens-ghc
 - cabal sandbox add-source microlens-th
 - cabal sandbox add-source microlens-platform

script:
 - cd microlens
 - cabal sandbox init --sandbox ../sandbox
 - cabal install --only-dependencies
 - cabal install --ghc-options=-Werror
 - cabal configure && cabal sdist
 - cd ..

 - cd microlens-mtl
 - cabal sandbox init --sandbox ../sandbox
 - cabal install --only-dependencies
 - cabal install --ghc-options=-Werror
 - cabal configure && cabal sdist
 - cd ..

 - cd microlens-ghc
 - cabal sandbox init --sandbox ../sandbox
 - cabal install --only-dependencies
 - cabal install --ghc-options=-Werror
 - cabal configure && cabal sdist
 - cd ..

 - cd microlens-th
 - cabal sandbox init --sandbox ../sandbox
 - cabal install --only-dependencies
 - cabal install --ghc-options=-Werror
 - cabal configure && cabal sdist
 - cd ..

 - cd microlens-platform
 - cabal sandbox init --sandbox ../sandbox
 - cabal install --only-dependencies
 - cabal install --ghc-options=-Werror
 - cabal configure && cabal sdist
 - cd ..
